import java.util.Scanner;
public class Main {
    public static void main(String[] args) {
        Scanner s=new Scanner(System.in);
        System.out.println("Enter Vehicle details:");
        System.out.print("Vehicle ID: ");
        String vehicleId=s.nextLine();
        System.out.print("Manufacturer: ");
        String manufacturer=s.nextLine();
        System.out.print("Model: ");
        String model=s.nextLine();
        System.out.print("Fuel Type: ");
        String fuelType=s.nextLine();
        System.out.print("Engine Size (Liters): ");
        float engineSize=s.nextFloat();
        System.out.print("Year of Manufacture: ");
        int yearOfManufacture=s.nextInt();
        System.out.print("Average Mileage (km/L): ");
        float averageMileage=s.nextFloat();
        System.out.print("Emission Rate (g/km): ");
        float emissionRate=s.nextFloat();
        s.nextLine();
        Vehicle vehicle=new Vehicle(vehicleId, manufacturer, model, fuelType, engineSize, yearOfManufacture, averageMileage, emissionRate);
        System.out.println("\nEnter Industry details:");
        System.out.print("Industry ID: ");
        String industryId=s.nextLine();
        System.out.print("Industry Name: ");
        String industryName=s.nextLine();
        System.out.print("Industry Type: ");
        String industryType=s.nextLine();
        System.out.print("Annual Energy Consumption (kWh): ");
        float annualEnergyConsumption=s.nextFloat();
        System.out.print("Annual Carbon Emissions (tons/year): ");
        float annualCarbonEmissions=s.nextFloat();
        s.nextLine();
        Industry industry=new Industry(industryId, industryName, industryType, annualEnergyConsumption, annualCarbonEmissions);
        System.out.println("\nEnter Energy Source details:");
        System.out.print("Energy Source ID: ");
        String energySourceId=s.nextLine();
        System.out.print("Source Name: ");
        String sourceName=s.nextLine();
        System.out.print("Source Type: ");
        String sourceType=s.nextLine();
        System.out.print("Carbon Footprint (kg/kWh): ");
        float carbonFootprint=s.nextFloat();
        s.nextLine();
        EnergySource energySource=new EnergySource(energySourceId, sourceName, sourceType, carbonFootprint);
        System.out.println("\nEnter Transport System details:");
        System.out.print("System ID: ");
        String systemId=s.nextLine();
        System.out.print("Type: ");
        String type=s.nextLine();
        System.out.print("Daily Passengers: ");
        int dailyPassengers=s.nextInt();
        s.nextLine();
        Transport transportSystem=new Transport(systemId, type, dailyPassengers);
        System.out.println("\nEnter Household details:");
        System.out.print("Household ID: ");
        String householdId=s.nextLine();
        System.out.print("Number of Residents: ");
        int numberOfResidents=s.nextInt();
        System.out.print("Monthly Electricity Usage (kWh): ");
        float monthlyElectricityUsage=s.nextFloat();
        s.nextLine();
        Household household=new Household(householdId, numberOfResidents, monthlyElectricityUsage);
        System.out.println("\nEnter Waste Management details:");
        System.out.print("Waste ID: ");
        String wasteId=s.nextLine();
        System.out.print("Waste Type: ");
        String wasteType=s.nextLine();
        System.out.print("Quantity Generated (tons/year): ");
        float quantityGenerated=s.nextFloat();
        s.nextLine();
        WasteManagement wasteManagement=new WasteManagement(wasteId, wasteType, quantityGenerated);
        System.out.println("\nEnter Air Quality details:");
        System.out.print("Record ID: ");
        String recordId=s.nextLine();
        System.out.print("Location: ");
        String location=s.nextLine();
        System.out.print("PM2.5 Level (µg/m³): ");
        float pm25Level=s.nextFloat();
        s.nextLine();
        AirQuality airQuality=new AirQuality(recordId, location, pm25Level);
        System.out.println("\nEnter Policy details:");
        System.out.print("Policy ID: ");
        String policyId=s.nextLine();
        System.out.print("Policy Name: ");
        String policyName=s.nextLine();
        System.out.print("Emission Reduction Goal (tons/year): ");
        float emissionReductionGoal=s.nextFloat();
        s.nextLine();
        Policy policy=new Policy(policyId, policyName, emissionReductionGoal);
        System.out.println("\nEnter Carbon Credit details:");
        System.out.print("Credit ID: ");
        String creditId=s.nextLine();
        System.out.print("Credit Amount (tons): ");
        float creditAmount=s.nextFloat();
        s.nextLine();
        CarbonCredit carbonCredit=new CarbonCredit(creditId, creditAmount);
        System.out.println("\nEnter User details:");
        System.out.print("User ID: ");
        String userId=s.nextLine();
        System.out.print("Username: ");
        String username=s.nextLine();
        System.out.print("Role: ");
        String role=s.nextLine();
        User user=new User(userId, username, role);
        System.out.println("\n----- Details Entered -----");
        vehicle.displayDetails();
        industry.displayDetails();
        energySource.displayDetails();
        transportSystem.displayDetails();
        household.displayDetails();
        wasteManagement.displayDetails();
        airQuality.displayDetails();
        policy.displayDetails();
        carbonCredit.displayDetails();
        user.displayDetails();
    }
}
